### PR TITLE
Fixed broken link in README.md Pro Tips section

### PR DESCRIPTION
**Pull request by FionaBronwen**
Updated README.md [Pro Tips](https://github.com/braintree/braintree_flask_example#pro-tips) section to include the correct link to documentation for generating your own custom secret key.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Looks like this repo uses Flask at 0.12. Can you change the link to `http://flask.pocoo.org/docs/0.12/quickstart/#sessions` instead? That looks like a real page.

Thanks for catching this!

**Comment by FionaBronwen** [comment]
Note:

Seeing the `RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.` in Travis because this PR is being opened from a fork which does not include the .env file. 

Thanks!

**Comment by crookedneighbor** [comment]
Yeah, that's what I'd expect to see in a PR from a fork of the project.

**Comment by FionaBronwen** [comment]
Should be up to date now. Thanks so much for your help @crookedneighbor !

**Comment by crookedneighbor** [comment]
Looks great.

**Pull request merged**
